-- DROP TABLE Pictures;

CREATE TABLE IF NOT EXISTS Pictures (
  pictureId   INT AUTO_INCREMENT PRIMARY KEY,
  userId      VARCHAR(255) NOT NULL,
  picture     VARCHAR(2048) NOT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (userId) REFERENCES Users(kakaoId)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);